"""
NOTE (added during refactor): This file is the original exploratory
research notebook, kept for historical reference only. It is NOT used
by the production codebase (see the project root and models/, data/,
explainability/ packages for the actual shipped implementation).

All API keys and tokens that were hardcoded in the original file have
been redacted below. If you had committed this notebook anywhere with
real credentials in it, rotate those credentials.
"""

# -*- coding: utf-8 -*-
"""Mini_Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/170d4W2RV9nNcgcCEHJrtJNOPmmTWWlrt
"""

import torch
torch.cuda.is_available()

from google.colab import drive
drive.mount('/content/drive')

base_path = "/content/drive/MyDrive/Deepfake_project/data"

import os

print("Train folders:", os.listdir(base_path + "/train"))
print("Val folders:", os.listdir(base_path + "/val"))

!pip install kaggle

import os

os.environ['KAGGLE_USERNAME'] = 'REDACTED'  # secret redacted during refactor
os.environ['KAGGLE_KEY'] = 'REDACTED'  # secret redacted during refactor

!pip install kaggle

!kaggle datasets list

!kaggle datasets download -d ciplab/real-and-fake-face-detection

"""!unzip real-and-fake-face-detection.zip -d dataset

!ls dataset
"""

!ls dataset/real_and_fake_face

import os
import shutil
import random

# Source paths
real_src = "dataset/real_and_fake_face/training_real"
fake_src = "dataset/real_and_fake_face/training_fake"

# Destination base
base_dest = "/content/drive/MyDrive/Deepfake_project/data"

# Make sure destination folders exist
for folder in ["train/real", "train/fake", "val/real", "val/fake"]:
    os.makedirs(os.path.join(base_dest, folder), exist_ok=True)

def split_and_move(src, train_dest, val_dest, split_ratio=0.8):
    files = os.listdir(src)
    random.shuffle(files)
    split_index = int(len(files) * split_ratio)

    train_files = files[:split_index]
    val_files = files[split_index:]

    for f in train_files:
        shutil.copy(os.path.join(src, f), train_dest)

    for f in val_files:
        shutil.copy(os.path.join(src, f), val_dest)

# Split real
split_and_move(
    real_src,
    base_dest + "/train/real",
    base_dest + "/val/real"
)

# Split fake
split_and_move(
    fake_src,
    base_dest + "/train/fake",
    base_dest + "/val/fake"
)

print("Dataset successfully split into train and validation!")

print("Train Real:", len(os.listdir(base_dest + "/train/real")))
print("Train Fake:", len(os.listdir(base_dest + "/train/fake")))
print("Val Real:", len(os.listdir(base_dest + "/val/real")))
print("Val Fake:", len(os.listdir(base_dest + "/val/fake")))

import torch
print(torch.cuda.is_available())

import torch
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms, models
from torch.utils.data import DataLoader

# Device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

# Path
base_path = "/content/drive/MyDrive/Deepfake_project/data"

# Transforms
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406],
                         [0.229, 0.224, 0.225])
])

# Load datasets
train_data = datasets.ImageFolder(base_path + "/train", transform=transform)
val_data = datasets.ImageFolder(base_path + "/val", transform=transform)

train_loader = DataLoader(train_data, batch_size=32, shuffle=True)
val_loader = DataLoader(val_data, batch_size=32)

# Load pretrained model
model = models.resnet18(pretrained=True)
model.fc = nn.Linear(model.fc.in_features, 2)
model = model.to(device)

# Loss & Optimizer
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.0001)

epochs = 5

for epoch in range(epochs):
    model.train()
    running_loss = 0
    correct = 0

    for images, labels in train_loader:
        images, labels = images.to(device), labels.to(device)

        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        running_loss += loss.item()
        _, preds = torch.max(outputs, 1)
        correct += torch.sum(preds == labels)

    train_acc = correct.double() / len(train_data)

    # Validation
    model.eval()
    val_correct = 0
    with torch.no_grad():
        for images, labels in val_loader:
            images, labels = images.to(device), labels.to(device)
            outputs = model(images)
            _, preds = torch.max(outputs, 1)
            val_correct += torch.sum(preds == labels)

    val_acc = val_correct.double() / len(val_data)

    print(f"Epoch {epoch+1}/{epochs}")
    print(f"Train Accuracy: {train_acc:.4f}")
    print(f"Validation Accuracy: {val_acc:.4f}")
    print("-" * 30)

# Save model
torch.save(model.state_dict(), "/content/drive/MyDrive/Deepfake_project/deepfake_model.pth")
print("Model saved successfully!")

transform_train = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(10),
    transforms.ColorJitter(brightness=0.2, contrast=0.2),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406],
                         [0.229, 0.224, 0.225])
])

transform_val = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406],
                         [0.229, 0.224, 0.225])
])

model = models.resnet18(pretrained=True)

for param in model.parameters():
    param.requires_grad = False

model.fc = nn.Sequential(
    nn.Linear(model.fc.in_features, 128),
    nn.ReLU(),
    nn.Dropout(0.5),
    nn.Linear(128, 2)
)

model = model.to(device)

train_data = datasets.ImageFolder(
    base_path + "/train",
    transform=transform_train
)

val_data = datasets.ImageFolder(
    base_path + "/val",
    transform=transform_val
)

optimizer = optim.Adam(model.fc.parameters(), lr=0.0001)

epochs = 8

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms, models
from torch.utils.data import DataLoader

# Device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

# Path
base_path = "/content/drive/MyDrive/Deepfake_project/data"

# =====================
# Transforms
# =====================

transform_train = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(10),
    transforms.ColorJitter(brightness=0.2, contrast=0.2),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406],
                         [0.229, 0.224, 0.225])
])

transform_val = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406],
                         [0.229, 0.224, 0.225])
])

# =====================
# Dataset Loading
# =====================

train_data = datasets.ImageFolder(base_path + "/train", transform=transform_train)
val_data = datasets.ImageFolder(base_path + "/val", transform=transform_val)

train_loader = DataLoader(train_data, batch_size=32, shuffle=True)
val_loader = DataLoader(val_data, batch_size=32)

print("Train images:", len(train_data))
print("Val images:", len(val_data))

# =====================
# Model Setup
# =====================

model = models.resnet18(pretrained=True)

# Freeze backbone
for param in model.parameters():
    param.requires_grad = False

# Replace final layer
model.fc = nn.Sequential(
    nn.Linear(model.fc.in_features, 128),
    nn.ReLU(),
    nn.Dropout(0.5),
    nn.Linear(128, 2)
)

model = model.to(device)

# =====================
# Loss & Optimizer
# =====================

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.fc.parameters(), lr=0.0001)

# =====================
# Training
# =====================

epochs = 8

for epoch in range(epochs):
    model.train()
    train_correct = 0

    for images, labels in train_loader:
        images, labels = images.to(device), labels.to(device)

        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        _, preds = torch.max(outputs, 1)
        train_correct += torch.sum(preds == labels)

    train_acc = train_correct.double() / len(train_data)

    # Validation
    model.eval()
    val_correct = 0
    with torch.no_grad():
        for images, labels in val_loader:
            images, labels = images.to(device), labels.to(device)
            outputs = model(images)
            _, preds = torch.max(outputs, 1)
            val_correct += torch.sum(preds == labels)

    val_acc = val_correct.double() / len(val_data)

    print(f"Epoch {epoch+1}/{epochs}")
    print(f"Train Accuracy: {train_acc:.4f}")
    print(f"Validation Accuracy: {val_acc:.4f}")
    print("-" * 30)

# =====================
# Save Model
# =====================

torch.save(model.state_dict(), "/content/drive/MyDrive/Deepfake_project/deepfake_model_improved.pth")
print("Improved model saved successfully!")

model = models.resnet18(pretrained=True)

# Freeze all layers first
for param in model.parameters():
    param.requires_grad = False

# Unfreeze last block
for param in model.layer4.parameters():
    param.requires_grad = True

# Replace final layer
model.fc = nn.Sequential(
    nn.Linear(model.fc.in_features, 128),
    nn.ReLU(),
    nn.Dropout(0.5),
    nn.Linear(128, 2)
)

model = model.to(device)

optimizer = optim.Adam(filter(lambda p: p.requires_grad, model.parameters()), lr=0.00005)

import torch
print("GPU Available:", torch.cuda.is_available())
print("GPU Name:", torch.cuda.get_device_name(0))

import torch
print("GPU Available:", torch.cuda.is_available())
print("GPU Name:", torch.cuda.get_device_name(0))

from google.colab import drive
drive.mount('/content/drive')

from google.colab import drive
drive.mount('/content/drive')

!rm -rf /content/drive

from google.colab import drive
drive.mount('/content/drive')

import torch
print("GPU Available:", torch.cuda.is_available())
print("GPU Name:", torch.cuda.get_device_name(0))

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms, models
from torch.utils.data import DataLoader

# Device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

base_path = "/content/drive/MyDrive/Deepfake_project/data"

# ---------------------
# Transforms
# ---------------------

transform_train = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(10),
    transforms.ColorJitter(brightness=0.2, contrast=0.2),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406],
                         [0.229, 0.224, 0.225])
])

transform_val = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406],
                         [0.229, 0.224, 0.225])
])

# ---------------------
# Dataset
# ---------------------

train_data = datasets.ImageFolder(base_path + "/train", transform=transform_train)
val_data = datasets.ImageFolder(base_path + "/val", transform=transform_val)

train_loader = DataLoader(train_data, batch_size=32, shuffle=True)
val_loader = DataLoader(val_data, batch_size=32)

# ---------------------
# Model
# ---------------------

model = models.resnet18(pretrained=True)

# Freeze everything
for param in model.parameters():
    param.requires_grad = False

# Unfreeze last block
for param in model.layer4.parameters():
    param.requires_grad = True

# Replace final layer
model.fc = nn.Sequential(
    nn.Linear(model.fc.in_features, 128),
    nn.ReLU(),
    nn.Dropout(0.5),
    nn.Linear(128, 2)
)

model = model.to(device)

# ---------------------
# Optimizer
# ---------------------

optimizer = optim.Adam(filter(lambda p: p.requires_grad, model.parameters()), lr=0.00005)
criterion = nn.CrossEntropyLoss()

# ---------------------
# Training
# ---------------------

epochs = 12

for epoch in range(epochs):
    model.train()
    train_correct = 0

    for images, labels in train_loader:
        images, labels = images.to(device), labels.to(device)

        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        _, preds = torch.max(outputs, 1)
        train_correct += torch.sum(preds == labels)

    train_acc = train_correct.double() / len(train_data)

    model.eval()
    val_correct = 0
    with torch.no_grad():
        for images, labels in val_loader:
            images, labels = images.to(device), labels.to(device)
            outputs = model(images)
            _, preds = torch.max(outputs, 1)
            val_correct += torch.sum(preds == labels)

    val_acc = val_correct.double() / len(val_data)

    print(f"Epoch {epoch+1}/{epochs}")
    print(f"Train Accuracy: {train_acc:.4f}")
    print(f"Validation Accuracy: {val_acc:.4f}")
    print("-" * 30)

torch.save(model.state_dict(), "/content/drive/MyDrive/Deepfake_project/deepfake_model_final.pth")
print("Final model saved!")

import os

base_path = "/content/drive/MyDrive/Deepfake_project/data"

print("Train Real Count:", len(os.listdir(base_path + "/train/real")))
print("Train Fake Count:", len(os.listdir(base_path + "/train/fake")))
print("Val Real Count:", len(os.listdir(base_path + "/val/real")))
print("Val Fake Count:", len(os.listdir(base_path + "/val/fake")))

!ls dataset/real_and_fake_face

import os
import shutil
import random

real_src = "dataset/real_and_fake_face/training_real"
fake_src = "dataset/real_and_fake_face/training_fake"

base_dest = "/content/drive/MyDrive/Deepfake_project/data"

# Create folders if not exist
for folder in ["train/real", "train/fake", "val/real", "val/fake"]:
    os.makedirs(os.path.join(base_dest, folder), exist_ok=True)

def split_and_move(src, train_dest, val_dest, split_ratio=0.8):
    files = os.listdir(src)
    random.shuffle(files)
    split_index = int(len(files) * split_ratio)

    train_files = files[:split_index]
    val_files = files[split_index:]

    for f in train_files:
        shutil.copy(os.path.join(src, f), train_dest)

    for f in val_files:
        shutil.copy(os.path.join(src, f), val_dest)

split_and_move(real_src, base_dest + "/train/real", base_dest + "/val/real")
split_and_move(fake_src, base_dest + "/train/fake", base_dest + "/val/fake")

print("Dataset split completed!")

print("Train Real:", len(os.listdir(base_dest + "/train/real")))
print("Train Fake:", len(os.listdir(base_dest + "/train/fake")))
print("Val Real:", len(os.listdir(base_dest + "/val/real")))
print("Val Fake:", len(os.listdir(base_dest + "/val/fake")))

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms, models
from torch.utils.data import DataLoader

# Device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

base_path = "/content/drive/MyDrive/Deepfake_project/data"

# ---------------------
# Transforms
# ---------------------

transform_train = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(10),
    transforms.ColorJitter(brightness=0.2, contrast=0.2),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406],
                         [0.229, 0.224, 0.225])
])

transform_val = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406],
                         [0.229, 0.224, 0.225])
])

# ---------------------
# Dataset
# ---------------------

train_data = datasets.ImageFolder(base_path + "/train", transform=transform_train)
val_data = datasets.ImageFolder(base_path + "/val", transform=transform_val)

train_loader = DataLoader(train_data, batch_size=32, shuffle=True)
val_loader = DataLoader(val_data, batch_size=32)

# ---------------------
# Model
# ---------------------

model = models.resnet18(pretrained=True)

# Freeze everything
for param in model.parameters():
    param.requires_grad = False

# Unfreeze last block
for param in model.layer4.parameters():
    param.requires_grad = True

# Replace final layer
model.fc = nn.Sequential(
    nn.Linear(model.fc.in_features, 128),
    nn.ReLU(),
    nn.Dropout(0.5),
    nn.Linear(128, 2)
)

model = model.to(device)

# ---------------------
# Optimizer
# ---------------------

optimizer = optim.Adam(filter(lambda p: p.requires_grad, model.parameters()), lr=0.00005)
criterion = nn.CrossEntropyLoss()

# ---------------------
# Training
# ---------------------

epochs = 12

for epoch in range(epochs):
    model.train()
    train_correct = 0

    for images, labels in train_loader:
        images, labels = images.to(device), labels.to(device)

        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        _, preds = torch.max(outputs, 1)
        train_correct += torch.sum(preds == labels)

    train_acc = train_correct.double() / len(train_data)

    model.eval()
    val_correct = 0
    with torch.no_grad():
        for images, labels in val_loader:
            images, labels = images.to(device), labels.to(device)
            outputs = model(images)
            _, preds = torch.max(outputs, 1)
            val_correct += torch.sum(preds == labels)

    val_acc = val_correct.double() / len(val_data)

    print(f"Epoch {epoch+1}/{epochs}")
    print(f"Train Accuracy: {train_acc:.4f}")
    print(f"Validation Accuracy: {val_acc:.4f}")
    print("-" * 30)

torch.save(model.state_dict(), "/content/drive/MyDrive/Deepfake_project/deepfake_model_final.pth")
print("Final model saved!")

from google.colab import drive
drive.mount('/content/drive')

import os

base_path = "/content/drive/MyDrive/Deepfake_project/data"

print("Train Real:", len(os.listdir(base_path + "/train/real")))
print("Train Fake:", len(os.listdir(base_path + "/train/fake")))
print("Val Real:", len(os.listdir(base_path + "/val/real")))
print("Val Fake:", len(os.listdir(base_path + "/val/fake")))

import torch

print("GPU Available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU Name:", torch.cuda.get_device_name(0))
else:
    print("GPU not detected")

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

import os

base_path = "/content/drive/MyDrive/Deepfake_project/data"

print("Train Real:", len(os.listdir(base_path + "/train/real")))
print("Train Fake:", len(os.listdir(base_path + "/train/fake")))
print("Val Real:", len(os.listdir(base_path + "/val/real")))
print("Val Fake:", len(os.listdir(base_path + "/val/fake")))

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms, models
from torch.utils.data import DataLoader

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

base_path = "/content/drive/MyDrive/Deepfake_project/data"

# Data Augmentation
transform_train = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(10),
    transforms.ColorJitter(brightness=0.2, contrast=0.2),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406],
                         [0.229, 0.224, 0.225])
])

transform_val = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406],
                         [0.229, 0.224, 0.225])
])

train_data = datasets.ImageFolder(base_path + "/train", transform=transform_train)
val_data = datasets.ImageFolder(base_path + "/val", transform=transform_val)

train_loader = DataLoader(train_data, batch_size=32, shuffle=True)
val_loader = DataLoader(val_data, batch_size=32)

model = models.resnet18(weights="DEFAULT")

# Freeze early layers
for param in model.parameters():
    param.requires_grad = False

# Unfreeze last two blocks
for param in model.layer3.parameters():
    param.requires_grad = True

for param in model.layer4.parameters():
    param.requires_grad = True

# Replace final layer
model.fc = nn.Sequential(
    nn.Linear(model.fc.in_features, 256),
    nn.ReLU(),
    nn.Dropout(0.5),
    nn.Linear(256, 2)
)

model = model.to(device)

optimizer = optim.Adam(
    filter(lambda p: p.requires_grad, model.parameters()),
    lr=0.00003
)

criterion = nn.CrossEntropyLoss()

epochs = 15

for epoch in range(epochs):
    model.train()
    train_correct = 0

    for images, labels in train_loader:
        images, labels = images.to(device), labels.to(device)

        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        _, preds = torch.max(outputs, 1)
        train_correct += torch.sum(preds == labels)

    train_acc = train_correct.double() / len(train_data)

    model.eval()
    val_correct = 0
    with torch.no_grad():
        for images, labels in val_loader:
            images, labels = images.to(device), labels.to(device)
            outputs = model(images)
            _, preds = torch.max(outputs, 1)
            val_correct += torch.sum(preds == labels)

    val_acc = val_correct.double() / len(val_data)

    print(f"Epoch {epoch+1}/{epochs}")
    print(f"Train Accuracy: {train_acc:.4f}")
    print(f"Validation Accuracy: {val_acc:.4f}")
    print("-" * 30)

torch.save(model.state_dict(), "/content/drive/MyDrive/Deepfake_project/deepfake_model_best.pth")
print("Best tuned model saved!")

import torch
from torchvision import transforms, models
from PIL import Image

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Load model
model = models.resnet18(weights=None)
model.fc = torch.nn.Sequential(
    torch.nn.Linear(model.fc.in_features, 256),
    torch.nn.ReLU(),
    torch.nn.Dropout(0.5),
    torch.nn.Linear(256, 2)
)

model.load_state_dict(torch.load("/content/drive/MyDrive/Deepfake_project/deepfake_model_best.pth"))
model = model.to(device)
model.eval()

transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406],
                         [0.229, 0.224, 0.225])
])

image_path = "/content/drive/MyDrive/Deepfake_project/ai_test.png"

image = Image.open(image_path).convert("RGB")
image = transform(image).unsqueeze(0).to(device)

with torch.no_grad():
    output = model(image)
    _, pred = torch.max(output, 1)

classes = ["Fake", "Real"]
print("Prediction:", classes[pred.item()])

import torch
from torchvision import transforms, models
from PIL import Image
import torch.nn.functional as F

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Load model
model = models.resnet18(weights=None)
model.fc = torch.nn.Sequential(
    torch.nn.Linear(model.fc.in_features, 256),
    torch.nn.ReLU(),
    torch.nn.Dropout(0.5),
    torch.nn.Linear(256, 2)
)

model.load_state_dict(torch.load("/content/drive/MyDrive/Deepfake_project/deepfake_model_best.pth"))
model = model.to(device)
model.eval()

transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406],
                         [0.229, 0.224, 0.225])
])

# Change image name here
image_path = "/content/drive/MyDrive/Deepfake_project/ai_test.png"

image = Image.open(image_path).convert("RGB")
image = transform(image).unsqueeze(0).to(device)

with torch.no_grad():
    output = model(image)
    probabilities = F.softmax(output, dim=1)
    confidence, pred = torch.max(probabilities, 1)

classes = ["Fake", "Real"]

print("Prediction:", classes[pred.item()])
print("Confidence: {:.2f}%".format(confidence.item() * 100))

!ls /content/drive/MyDrive/Deepfake_project

!ls /content/drive/MyDrive

from google.colab import drive
drive.mount('/content/drive')

import torch
from torchvision import transforms, models
from PIL import Image
import torch.nn.functional as F

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Load model
model = models.resnet18(weights=None)
model.fc = torch.nn.Sequential(
    torch.nn.Linear(model.fc.in_features, 256),
    torch.nn.ReLU(),
    torch.nn.Dropout(0.5),
    torch.nn.Linear(256, 2)
)

model.load_state_dict(torch.load("/content/drive/MyDrive/Deepfake_project/deepfake_model_best.pth"))
model = model.to(device)
model.eval()

transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406],
                         [0.229, 0.224, 0.225])
])

# Change image name here
image_path = "/content/drive/MyDrive/Deepfake_project/test.png"

image = Image.open(image_path).convert("RGB")
image = transform(image).unsqueeze(0).to(device)

with torch.no_grad():
    output = model(image)
    probabilities = F.softmax(output, dim=1)
    confidence, pred = torch.max(probabilities, 1)

classes = ["Fake", "Real"]

print("Prediction:", classes[pred.item()])
print("Confidence: {:.2f}%".format(confidence.item() * 100))

!ls /content/drive/MyDrive

!ls /content/drive/MyDrive/*

!mv "/content/drive/MyDrive/Deepfake_project/test (1).png" \
    "/content/drive/MyDrive/Deepfake_project/test.png"

!ls /content/drive/MyDrive/Deepfake_project

import torch
from torchvision import transforms, models
from PIL import Image
import torch.nn.functional as F

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Load model
model = models.resnet18(weights=None)
model.fc = torch.nn.Sequential(
    torch.nn.Linear(model.fc.in_features, 256),
    torch.nn.ReLU(),
    torch.nn.Dropout(0.5),
    torch.nn.Linear(256, 2)
)

model.load_state_dict(torch.load("/content/drive/MyDrive/Deepfake_project/deepfake_model_best.pth"))
model = model.to(device)
model.eval()

transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406],
                         [0.229, 0.224, 0.225])
])

# Change image path here
image_path = "/content/drive/MyDrive/Deepfake_project/test.png"

image = Image.open(image_path).convert("RGB")
image = transform(image).unsqueeze(0).to(device)

with torch.no_grad():
    output = model(image)
    probabilities = F.softmax(output, dim=1)
    confidence, pred = torch.max(probabilities, 1)

classes = ["Fake", "Real"]
prediction = classes[pred.item()]
confidence_percent = confidence.item() * 100

# -------------------------
# Explanation Module
# -------------------------

if confidence_percent > 85:
    risk_level = "High"
    explanation = "The model detected strong visual patterns associated with synthetic textures and facial inconsistencies."
elif confidence_percent > 70:
    risk_level = "Moderate"
    explanation = "The model identified some irregular texture patterns, but confidence is not extremely high."
else:
    risk_level = "Low"
    explanation = "The prediction confidence is low. The model is uncertain due to limited distinguishing features."

print("Prediction:", prediction)
print("Confidence: {:.2f}%".format(confidence_percent))
print("Risk Level:", risk_level)
print("Explanation:", explanation)

import os

base_path = "/content/drive/MyDrive/Deepfake_project/data"

print("Train Real:", len(os.listdir(base_path + "/train/real")))
print("Train Fake:", len(os.listdir(base_path + "/train/fake")))
print("Val Real:", len(os.listdir(base_path + "/val/real")))
print("Val Fake:", len(os.listdir(base_path + "/val/fake")))

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms, models
from torch.utils.data import DataLoader
from google.colab import drive

# Mount drive
drive.mount('/content/drive')

# Dataset path
data_dir = "/content/drive/MyDrive/Deepfake_project/cropped_data"

# Image transforms
train_transform = transforms.Compose([
    transforms.Resize((224,224)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(10),
    transforms.ToTensor(),
])

val_transform = transforms.Compose([
    transforms.Resize((224,224)),
    transforms.ToTensor(),
])

# Datasets
train_dataset = datasets.ImageFolder(data_dir + "/train", transform=train_transform)
val_dataset = datasets.ImageFolder(data_dir + "/val", transform=val_transform)

# Dataloaders
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=32)

print("Train size:", len(train_dataset))
print("Val size:", len(val_dataset))

# Device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

# Model
model = models.resnet18(weights="IMAGENET1K_V1")
model.fc = nn.Linear(model.fc.in_features, 2)
model = model.to(device)

# Loss and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.0001)

epochs = 15

for epoch in range(epochs):

    model.train()
    train_correct = 0

    for images, labels in train_loader:

        images, labels = images.to(device), labels.to(device)

        optimizer.zero_grad()

        outputs = model(images)
        loss = criterion(outputs, labels)

        loss.backward()
        optimizer.step()

        _, preds = torch.max(outputs, 1)
        train_correct += torch.sum(preds == labels)

    train_acc = train_correct.double() / len(train_dataset)

    # Validation
    model.eval()
    val_correct = 0

    with torch.no_grad():

        for images, labels in val_loader:

            images, labels = images.to(device), labels.to(device)

            outputs = model(images)
            _, preds = torch.max(outputs, 1)

            val_correct += torch.sum(preds == labels)

    val_acc = val_correct.double() / len(val_dataset)

    print(f"Epoch {epoch+1}/{epochs}")
    print("Train Accuracy:", train_acc.item())
    print("Validation Accuracy:", val_acc.item())
    print("------------------------")

# Save model
torch.save(model.state_dict(), "/content/drive/MyDrive/Deepfake_project/resnet18_deepfake.pth")

print("🔥 ResNet18 model saved!")

import torch
print(torch.cuda.is_available())

import torch
from torchvision import transforms, models
from PIL import Image

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = models.resnet18(weights=None)
model.fc = torch.nn.Linear(model.fc.in_features, 2)

model.load_state_dict(torch.load("/content/drive/MyDrive/Deepfake_project/resnet18_deepfake.pth", map_location=device))
model.to(device)
model.eval()

transform = transforms.Compose([
    transforms.Resize((224,224)),
    transforms.ToTensor()
])

img = Image.open("/content/drive/MyDrive/Deepfake_project/Screenshot 2026-02-27 214404.png").convert("RGB")

img = transform(img).unsqueeze(0).to(device)

with torch.no_grad():
    output = model(img)
    _, pred = torch.max(output,1)

classes = ["Fake","Real"]
print("Prediction:", classes[pred.item()])

"""# ------------------------------
# NEW DATASET TRAINING
# ------------------------------
"""

!pip install kaggle

from google.colab import files
files.upload()

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download manjilkarki/deepfake-and-real-images

!unzip deepfake-and-real-images.zip

!ls

!ls real_and_fake_face

!ls Dataset

!ls Dataset/Train

from torchvision import datasets, transforms
from torch.utils.data import DataLoader

transform = transforms.Compose([
    transforms.Resize((224,224)),
    transforms.ToTensor()
])

train_dataset = datasets.ImageFolder(
    "Dataset/Train",
    transform=transform
)

val_dataset = datasets.ImageFolder(
    "Dataset/Validation",
    transform=transform
)

train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=32)

print("Classes:", train_dataset.classes)
print("Train size:", len(train_dataset))
print("Validation size:", len(val_dataset))

import torch
import torchvision.models as models
import torch.nn as nn

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = models.resnet18(weights="IMAGENET1K_V1")

model.fc = nn.Linear(model.fc.in_features,2)

model = model.to(device)

print("Model Loaded")

!nvidia-smi

import torch.optim as optim

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.0001)

epochs = 5

for epoch in range(epochs):

    model.train()
    running_loss = 0

    for i,(images,labels) in enumerate(train_loader):

        images = images.to(device)
        labels = labels.to(device)

        optimizer.zero_grad()

        outputs = model(images)
        loss = criterion(outputs,labels)

        loss.backward()
        optimizer.step()

        running_loss += loss.item()

        if i % 500 == 0:
            print(f"Epoch {epoch+1} Batch {i} Loss {loss.item():.4f}")

    print(f"Epoch {epoch+1} finished Loss {running_loss:.4f}")

torch.save(model.state_dict(), "deepfake_resnet18.pth")

from google.colab import files
files.upload()

import torch
import torchvision.models as models
import torch.nn as nn

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = models.resnet18(weights="IMAGENET1K_V1")
model.fc = nn.Linear(model.fc.in_features,2)

model.load_state_dict(torch.load("deepfake_resnet18.pth", map_location=device))
model = model.to(device)

model.eval()

print("Model loaded successfully")

from PIL import Image
import torch.nn.functional as F

# transform same as training
transform = transforms.Compose([
    transforms.Resize((224,224)),
    transforms.ToTensor()
])

img = Image.open("WhatsApp Image 2026-03-07 at 9.01.07 PM.jpeg").convert("RGB")

img = transform(img).unsqueeze(0).to(device)

with torch.no_grad():
    output = model(img)

prob = F.softmax(output, dim=1)

fake_prob = prob[0][0].item()
real_prob = prob[0][1].item()

print("Fake probability:", fake_prob)
print("Real probability:", real_prob)

if fake_prob > real_prob:
    print("Prediction: Fake")
else:
    print("Prediction: Real")

from google.colab import files
files.upload()

from PIL import Image
import torch.nn.functional as F

# transform same as training
transform = transforms.Compose([
    transforms.Resize((224,224)),
    transforms.ToTensor()
])

img = Image.open("Screenshot 2026-02-27 214404.png").convert("RGB")

img = transform(img).unsqueeze(0).to(device)

with torch.no_grad():
    output = model(img)

prob = F.softmax(output, dim=1)

fake_prob = prob[0][0].item()
real_prob = prob[0][1].item()

print("Fake probability:", fake_prob)
print("Real probability:", real_prob)

if fake_prob > real_prob:
    print("Prediction: Fake")
else:
    print("Prediction: Real")

img = Image.open("Dataset/Test/Fake/fake_1.jpg").convert("RGB")

from PIL import Image
import torch.nn.functional as F

img = Image.open("Dataset/Test/Fake/test.png").convert("RGB")

img = transform(img).unsqueeze(0).to(device)

with torch.no_grad():
    output = model(img)

prob = F.softmax(output, dim=1)

fake_prob = prob[0][0].item()
real_prob = prob[0][1].item()

print("Fake probability:", fake_prob)
print("Real probability:", real_prob)

confidence = max(fake_prob, real_prob) * 100

if fake_prob > real_prob:
    prediction = "Fake"
else:
    prediction = "Real"

print("Prediction:", prediction)
print("Confidence:", confidence)

print("\nAI Explanation:\n")
print(llm_explanation(prediction, confidence))

!ls "/content/drive/MyDrive/Deepfake_project/data/val/fake"

from google.colab import drive
drive.mount('/content/drive')

from google.colab import files
files.download("deepfake_resnet18.pth")

"""

---

# LLM IMPLEMENTATION

---





"""

!pip install google-generativeai

import google.generativeai as genai

genai.configure(api_key="REDACTED")  # secret redacted during refactor

model_llm = genai.GenerativeModel("gemini-1.5-flash")

!pip uninstall google-generativeai -y

!pip install google-genai

from google import genai

client = genai.Client(api_key="REDACTED")  # secret redacted during refactor

from torchvision import transforms

transform = transforms.Compose([
    transforms.Resize((224,224)),
    transforms.ToTensor()
])

def llm_explanation(prediction, confidence):

    if prediction == "Fake":
        return f"""
The AI model classified this image as FAKE with {confidence:.2f}% confidence.

Deepfake images often contain artifacts such as unnatural facial textures,
inconsistent lighting, irregular blending around facial edges, or abnormal
eye and mouth movements which the model may have detected.
"""

    else:
        return f"""
The AI model classified this image as REAL with {confidence:.2f}% confidence.

Real images typically contain natural facial textures, consistent lighting,
and normal structural patterns which the model recognized.
"""

import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

import torch
import torch.nn as nn
import torchvision.models as models

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

model = models.resnet18(weights=None)
model.fc = nn.Linear(model.fc.in_features, 2)

model.load_state_dict(torch.load("/content/drive/MyDrive/Deepfake_project/resnet18_deepfake.pth", map_location=device))

model = model.to(device)
model.eval()

from torchvision import transforms

transform = transforms.Compose([
    transforms.Resize((224,224)),
    transforms.ToTensor()
])

from PIL import Image
import torch.nn.functional as F

img = Image.open("/content/drive/MyDrive/Deepfake_project/data/val/fake/easy_100_1111.jpg").convert("RGB")

img = transform(img).unsqueeze(0).to(device)

with torch.no_grad():
    output = model(img)

prob = F.softmax(output, dim=1)

fake_prob = prob[0][0].item()
real_prob = prob[0][1].item()

print("Fake probability:", fake_prob)
print("Real probability:", real_prob)

confidence = max(fake_prob, real_prob) * 100

if fake_prob > real_prob:
    prediction = "Fake"
else:
    prediction = "Real"

print("Prediction:", prediction)
print("Confidence:", round(confidence,2), "%")

print("\nAI Explanation:\n")
print(llm_explanation(prediction, confidence))

!pip install streamlit

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import torch
# import torch.nn as nn
# import torchvision.models as models
# from torchvision import transforms
# from PIL import Image
# import torch.nn.functional as F
# 
# # Device
# device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# 
# # Load model
# model = models.resnet18(weights=None)
# model.fc = nn.Linear(model.fc.in_features, 2)
# 
# model.load_state_dict(torch.load("resnet18_deepfake.pth", map_location=device))
# model = model.to(device)
# model.eval()
# 
# # Transform
# transform = transforms.Compose([
#     transforms.Resize((224,224)),
#     transforms.ToTensor()
# ])
# 
# # Explanation function
# def explain(prediction, confidence):
#     if prediction == "Fake":
#         return f"""
# This image is predicted as FAKE with {confidence:.2f}% confidence.
# 
# Deepfake images may contain unnatural facial textures,
# lighting inconsistencies, or blending artifacts.
# """
#     else:
#         return f"""
# This image is predicted as REAL with {confidence:.2f}% confidence.
# 
# The facial features appear natural and consistent.
# """
# 
# # UI
# st.title("Deepfake Detection System")
# 
# uploaded_file = st.file_uploader("Upload an Image", type=["jpg","png","jpeg"])
# 
# if uploaded_file is not None:
# 
#     image = Image.open(uploaded_file).convert("RGB")
#     st.image(image, caption="Uploaded Image", use_column_width=True)
# 
#     img = transform(image).unsqueeze(0).to(device)
# 
#     with torch.no_grad():
#         output = model(img)
# 
#     prob = F.softmax(output, dim=1)
# 
#     fake_prob = prob[0][0].item()
#     real_prob = prob[0][1].item()
# 
#     confidence = max(fake_prob, real_prob) * 100
# 
#     if fake_prob > real_prob:
#         prediction = "Fake"
#     else:
#         prediction = "Real"
# 
#     st.subheader(f"Prediction: {prediction}")
#     st.write(f"Confidence: {confidence:.2f}%")
# 
#     st.subheader("AI Explanation")
#     st.write(explain(prediction, confidence))

!streamlit run app.py

!pip install pyngrok

from pyngrok import ngrok

!streamlit run app.py &>/dev/null &

public_url = ngrok.connect(8501)
print(public_url)

!ngrok config add-authtoken REDACTED  # secret redacted during refactor

!streamlit run app.py &>/dev/null &

from pyngrok import ngrok

public_url = ngrok.connect(8501)
print(public_url)

!ls -lh resnet18_deepfake.pth

!ls

"""https://deepfake-detection-system-ramm.streamlit.app/"""